# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab3/PYNQ-Z1_C.xdc

# Block Designs: bd/Lab_3/Lab_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3 || ORIG_REF_NAME==Lab_3} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_processing_system7_0_0/Lab_3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_processing_system7_0_0 || ORIG_REF_NAME==Lab_3_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_axi_regmap_0_0/Lab_3_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_axi_regmap_0_0 || ORIG_REF_NAME==Lab_3_axi_regmap_0_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_Multiplication_0_0/Lab_3_Multiplication_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_Multiplication_0_0 || ORIG_REF_NAME==Lab_3_Multiplication_0_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_ps7_0_axi_periph_0/Lab_3_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab_3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_rst_ps7_0_100M_0/Lab_3_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab_3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_xlslice_0_0/Lab_3_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_xlslice_0_0 || ORIG_REF_NAME==Lab_3_xlslice_0_0} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_xlslice_0_1/Lab_3_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_xlslice_0_1 || ORIG_REF_NAME==Lab_3_xlslice_0_1} -quiet] -quiet

# IP: bd/Lab_3/ip/Lab_3_auto_pc_0/Lab_3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_3_auto_pc_0 || ORIG_REF_NAME==Lab_3_auto_pc_0} -quiet] -quiet

# XDC: bd/Lab_3/Lab_3_ooc.xdc
